

name: celeb_project
description: A new Flutter application.

version: 2.0.2
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  like_button: ^2.0.4
  flutter_svg: ^1.0.3
  step_progress_indicator: ^1.0.2
  simple_animations: ^4.0.1
  dropdown_button2: ^1.2.0
  flutter_form_builder: ^7.1.1
  cupertino_icons: ^1.0.4
  datetime_picker_formfield: ^2.0.0
  table_calendar: ^3.0.4
  intl: ">=0.17.0 <1.0.0"
  responsive_framework: ^0.1.7
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: 1.0.1
  flutter_rounded_date_picker: ^2.0.2
  sizer: ^2.0.15
  flutter_screenutil: ^5.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/Icons/Pass Icon.svg
    - assets/Icons/Trailing Icon.svg
    - assets/Icons/Frame 3343.svg
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: fonts/FontsFree-Net-SFProDisplay-Medium.ttf
